<?php
/**
 * Checkout.com Magento 2 Payment module (https://www.checkout.com)
 *
 * Copyright (c) 2017 Checkout.com (https://www.checkout.com)
 * Author: David Fiaty | integration@checkout.com
 *
 * License GNU/GPL V3 https://www.gnu.org/licenses/gpl-3.0.en.html
 */
?>
 
<script src="<?php echo $block->getEmbeddedUrl(); ?>"></script>

<?php
// Load default CSS only if there is no custom file in config
if (!$block->hasCustomCss()) {
?>
	<style>
		@import url(<?php echo $block->getEmbeddedCss(); ?>);
	</style>
<?php
}
?>

<style>
	html {
	    overflow: -moz-scrollbars-vertical !important; 
	    overflow-y: scroll !important;
	}

	#embeddedForm {
		z-index: 0 !important;
	}
	
	#embeddedForm, #embeddedForm iframe {
	    position: relative !important;
	}

	#embeddedForm iframe {
		min-height: 153px;
	}

	@media all and (min-width: 520px) {
		#cko-form-holder {
			max-width: 60%;
		}
	}	

	@media all and and (min-width: 301px) and (max-width: 519px) {
		#cko-form-holder {
			max-width: 80%;
		}
	}	

	@media all and (max-width: 300px) {
		#cko-form-holder {
			max-width: 100%;
		}
	}	
</style>