<?php
/**
 * Checkout.com
 * Authorized and regulated as an electronic money institution
 * by the UK Financial Conduct Authority (FCA) under number 900816.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Checkout.com
 * @author    Platforms Development Team <platforms@checkout.com>
 * @copyright 2010-present Checkout.com
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://docs.checkout.com/
 */

use CheckoutCom\Magento2\Controller\Apm\DisplaySepa;
use Magento\Framework\Escaper;

/**
 * @var DisplaySepa $block
 * @var Escaper $escaper
 */
?>

<input type="hidden" name="source" value="sepa" required>
<div class="sepa-mandate-card">
    <div class="sepa-card-header">
        <div class="sepa-card-header-text">
            <div class="sepa-card-title">
                <h3><?= $escaper->escapeHtml(__('SEPA Direct Debit Mandate for single payment')) ?></h3>
            </div>
        </div>
    </div>
    <div class="sepa-mandate-content">
        <div class="sepa-creditor">
            <h2><?= $escaper->escapeHtml(__('Creditor')) ?></h2>
            <h3><?= $escaper->escapeHtml($block->getData('store')->getName()); ?></h3>
            <p class="ng-star-inserted"><?= $escaper->escapeHtml($block->getData('store')->getStreetLine(1)); ?></p>
            <p><?= $escaper->escapeHtml($block->getData('store')->getStreetLine(2)); ?></p>
            <p><?= $escaper->escapeHtml(($block->getData('store')->getPostcode() . ' ' . $block->getData('store')->getCity())); ?></p>
            <p><?= $escaper->escapeHtml($block->getData('store')->getCountry()); ?></p>
            <br>
            <p class="monospace"><?= $escaper->escapeHtml((__('Creditor ID') . ': ' . $block->getData('reference'))) ?></p>
        </div>
        <div class="sepa-debitor">
            <h2><?= $escaper->escapeHtml(__('Debitor')) ?></h2>
            <h3><?= $escaper->escapeHtml(($block->getData('billingAddress')->getFirstname() . ' ' . $block->getData('billingAddress')->getLastname())); ?></h3>
            <div class="address">
                <p class="ng-star-inserted"><?= $escaper->escapeHtml($block->getData('billingAddress')->getStreetLine(1)); ?></p>
                <p><?= $escaper->escapeHtml($block->getData('billingAddress')->getStreetLine(2)); ?></p>
                <p><?= $escaper->escapeHtml(($block->getData('billingAddress')->getPostcode() . ' ' . $block->getData('billingAddress')->getCity())); ?></p>
                <p><?= $escaper->escapeHtml($block->getData('billingAddress')->getCountry()); ?></p>
            </div>
            <br>
            <p class="monospace" id="sepa-dd-bic"></p>
            <p class="monospace" id="sepa-dd-iban"></p>
        </div>
    </div>
    <div class="sepa-par">
        <hr>
        <p><?= $escaper->escapeHtml(__('By accepting this mandate form, you authorise (A) b4payment GmbH to send instructions to your bank to debit your account (B) your bank to debit your account in accordance with the instructions from b4payment GmbH.'))?></p>
        <p><?= $escaper->escapeHtml(__('As part of your rights, you are entitled to a refund from your bank under the terms and conditions of your agreement with your bank. A refund must be claimed within 8 weeks starting from the date on which your account was debited.'))?>
        </p>
        <div class="sepa-checkbox-container" id="sepa-checkbox-container">
            <label class="sepa-checkbox-layout" for="sepa-checkbox-input">
                <span class="sepa-checkbox-inner-container">
                    <input class="sepa-checkbox-input" type="checkbox" id="sepa-checkbox-input" name="accepted" value="1" required>
                    <h4><?= $escaper->escapeHtml(__('I accept the mandate for a single payment')) ?></h4>
                    <input type="hidden" name="url" value="<?= $escaper->escapeUrl($block->getData('url')) ?>"required>
                </span>
            </label>
        </div>
    </div>

    <div class="sepa-right">
        <hr>
        <div class="sepa-card-footer">
            <div class="sepa-card-footer-text">
                <div class="sepa-footer-title">
                <?= $escaper->escapeHtml(__('Your rights regarding the above mandate are explained in a statement that you can obtain from your bank.')) ?>
                </div>
            </div>
        </div>
    </div>
</div>

