<?php

/**
 * @var $block \CheckoutCom\Magento2\Block\Adminhtml\Order\View\View
 */

$avsCheck = $block->getCkoPaymentData('avs_check');
$cvvCheck = $block->getCkoPaymentData('cvv_check');
$threeDsCode = $block->getCko3dsPaymentData('authentication_response');
$issuer = $block->getCkoPaymentData('issuer');
$threeDsVersion = $block->getCko3dsPaymentData('version');
?>
<div class="order-account-information">
    <div class="field-email">
        <div class="admin__page-section-title">
            <h2 class="title"><?= $block->escapeHtml(__('Payment Additional Information')) ?></h2>
        </div>
        <table class="admin__table-secondary order-information-table">
            <tr>
                <th><?= $block->escapeHtml(__('Card type')) ?></th>
                <td><?= $block->getCkoPaymentData('scheme') ?> (<?= $block->getCkoPaymentData('product_type') ?>)</td>
            </tr>
            <tr>
                <th><?= $block->escapeHtml(__('Card 4 last numbers')) ?></th>
                <td>**** **** **** <?= $block->getCkoPaymentData('last4') ?></td>
            </tr>
            <tr>
                <th><?= $block->escapeHtml(__('Card expiry (mm/yy)')) ?></th>
                <td><?= $block->getCkoPaymentData('expiry_month') ?>/<?= $block->getCkoPaymentData('expiry_year') ?></td>
            </tr>
            <tr>
                <th><?= $block->escapeHtml(__('Card Country')) ?></th>
                <td><?= $block->getCkoPaymentData('issuer_country') ?></td>
            </tr>
            <?php if ($issuer): ?>
            <tr>
                <th><?= $block->escapeHtml(__('Issuing Bank')) ?></th>
                <td><?= $issuer ?></td>
            </tr>
            <?php endif; ?>
            <?php if ($avsCheck): ?>
            <tr>
                <th><?= $block->escapeHtml(__('AVS Check')) ?></th>
                <td><?= $avsCheck ?> (<?= $block->getAvsCheckDescription($avsCheck) ?>)</td>
            </tr>
            <?php endif; ?>
            <?php if ($cvvCheck): ?>
            <tr>
                <th><?= $block->escapeHtml(__('CVV Check')) ?></th>
                <td><?= $cvvCheck ?> (<?= $block->getCvvCheckDescription($cvvCheck) ?>)</td>
            </tr>
            <?php endif; ?>
            <?php if ($threeDsCode): ?>
            <tr>
                <th><?= $block->escapeHtml(__('3DS authorization code')) ?></th>
                <td><?= $threeDsCode ?> (<?= $block->get3dsDescription($threeDsCode) ?>)</td>
            </tr>
            <?php endif; ?>
            <?php if ($threeDsVersion): ?>
            <tr>
                <th><?= $block->escapeHtml(__('3DS version')) ?></th>
                <td><?= $threeDsVersion ?></td>
            </tr>
            <?php endif; ?>
        </table>
    </div>
</div>
