<?php
/**
* @var $block \CheckoutCom\Magento2\Block\Adminhtml\Order\View\View
*/

$order = $block->getOrder();
?>

<div>
   <h2><?php echo $block->sectionName()?></h2>
   <p>Card type : <?= $block->getCardType($order) ?> </p> 
   <p>Card 4 last numbers : <?= $block->getFourDigits($order) ?></p>
   <p>Card expiry month :<?= $block->getCardExpiryMonth($order)?> </p>
   <p>Card expiry year : <?= $block->getCardExpiryYear($order)?></p>
   <p>Card Bank : </p><?= "Société générale" ?>
   <p>Card Country : </p><?= "FR" ?>
   <p>Mismatched Adress (fraud check) : </p><?= "No Fraud"?>
   <p> Payment Method refunded : </p><?= "MasterCard" ?>
   <p>3DSecure success : </p><?= "ok" ?>
</div>
