
<button id="ckoShowForm" class="action submit primary">
	<!-- ko i18n: 'Add Credit Card (checkout.com)'--><!-- /ko -->
</button>

<div id="cko-form-holder" style="display: none;">
    <form class="widget-container" id="saveCardForm" method="POST">
        <?php echo $block->getBlockHtml('formkey')?>
        <input type="hidden" id="ckoCardToken" name="ckoCardToken">
    </form>
</div>
<button id="ckoSaveCard" type="button" class="action primary"  title="<?= $block->escapeHtmlAttr(__('Save the card')) ?>" style="display: none;">
    <?= $block->escapeHtml(__('Save the card')) ?>
</button>

<script type="text/javascript">
    require(['jquery', 'domReady!', 'framesjs'], function ($) {
        // Prepare the elements
        var saveCardButton = $('#ckoSaveCard');
        var showFormButton = $('#ckoShowForm');
        var cardTokenField = $('#ckoCardToken');
        var cardFormContainerId = '#cko-form-holder';
        var ckoPublicKey = '<?= $block->config->getValue('public_key'); ?>';
        var paymentForm = document.getElementById('saveCardForm');
        var ckoTheme = '';
        
        // Todo - Connect the  debug mode to config
        var ckoDebugMode = false;

        // Initialize the embedded form
        Frames.init({
            publicKey: ckoPublicKey,
            containerSelector: cardFormContainerId,
            theme: ckoTheme,
            debugMode: ckoDebugMode,
            frameActivated: function () {
                saveCardButton.attr("disabled", true);
            },
            cardValidationChanged: function(event) {
                if (Frames.isCardValid()) {
                    saveCardButton.attr("disabled", false);
                    Frames.submitCard();
                    Frames.unblockFields();
                }
            },
            cardTokenised: function(event) {                        
                // Add the card token to the form
                Frames.addCardToken(paymentForm, event.data.cardToken);

                // Add the card token to the hidden input field
                cardTokenField.val(event.data.cardToken);
            }
        });  

        // Add card form controls
        showFormButton.on('click touch', function (event) {
            $(cardFormContainerId).show();
            saveCardButton.show();
            showFormButton.hide();
        });

        // Handle the submit event
        saveCardButton.on('click touch', function (event) {
            // Disable the save button
            saveCardButton.attr("disabled", true);

            // Prevent default events
            event.preventDefault();

            // Send the request
            $.ajax({
                type: 'POST',
                url: '<?= $block->getUrl('checkout_com/account/savecard'); ?>',
                data: {cardToken: cardTokenField.val()},
                success: function (data) {
                    if (!data.success) {
                        // Todo - handle error message display
                        //FullScreenLoader.stopLoader();
                        //self.showMessage('error', data.message);
                    }
                    else if (data.success && data.url) {
                        // Todo - handle3 DS redirection
                        window.location.href = data.url
                    }
                },
                error: function (request, status, error) {
                   // Todo - handle error message display
                   //FullScreenLoader.stopLoader();
                   // self.showMessage('error', error);
                }
            });
        });
    });
</script>