
<button id="cko-show-card-form" class="action submit primary">
	<!-- ko i18n: 'Add Credit Card (checkout.com)'--><!-- /ko -->
</button>

<div id="cko-form-holder" style="display: none;">
    <form class="widget-container" id="saveCardForm" method="POST" action="<?= $block->getUrl('checkoutcom/account/savecard'); ?>"></form>
</div>
<button id="cko-save-card" type="button" class="action primary"  title="<?= $block->escapeHtmlAttr(__('Save the card')) ?>" style="display: none;">
    <?= $block->escapeHtml(__('Save the card')) ?>
</button>

<script type="text/javascript">
    require(['jquery', 'domReady!', 'framesjs'], function ($) {
        // Prepare the elements
        var saveCardButton = $('#cko-save-card');
        var showFormButton = $('#cko-show-card-form');
        var cardFormContainerId = '#cko-form-holder';
        var ckoPublicKey = '<?= $block->config->getValue('public_key'); ?>';
        var paymentForm = document.getElementById('saveCardForm');
        var ckoTheme = '';
        var ckoDebugMode = false;

        // Add card form controls
        showFormButton.on('click touch', function (event) {
            $(cardFormContainerId).show();
            saveCardButton.show();
            showFormButton.hide();
        });

        // Handle the submit event
        saveCardButton.on('click touch', function (event) {
            $('.loading-mask').show();
            event.preventDefault();
            Frames.submitCard();
        });

        // Initialize the embedded form
        Frames.init({
            publicKey: ckoPublicKey,
            containerSelector: cardFormContainerId,
            theme: ckoTheme,
            debugMode: ckoDebugMode,
            frameActivated: function () {
                saveCardButton.attr("disabled", true);
            },
            cardSubmitted: function() {
                saveCardButton.attr("disabled", true);
            },
            cardValidationChanged: function(event) {
                saveCardButton.attr("disabled", !Frames.isCardValid());
            },
            cardTokenised: function(event) {                        
                // Add the card token to the form
                Frames.addCardToken(paymentForm, event.data.cardToken);

                // Submit the payment form
                paymentForm.submit();
            },
        });  
    });
</script>