
<button id="ckoShowForm" class="action submit primary">
    <?= $block->escapeHtml(__('Add a card')) ?>
</button>

<div id="cko-form-holder" style="display: none;">
    <form class="widget-container" id="saveCardForm" method="POST">
        <?= $block->getBlockHtml('formkey') ?>
        <input type="hidden" id="ckoCardToken" name="ckoCardToken">
    </form>
</div>
<button id="ckoSaveCard" type="button" class="action primary"  title="<?= $block->escapeHtmlAttr(__('Save the card')) ?>" style="display: none;">
    <?= $block->escapeHtml(__('Save the card')) ?>
</button>

<script type="text/javascript">
    require([
        'jquery',
        'domReady!',
        'framesjs'
    ], function ($) {
        // Prepare the elements
        var saveCardButton = $('#ckoSaveCard');
        var showFormButton = $('#ckoShowForm');
        var cardTokenField = $('#ckoCardToken');
        var cardFormContainerId = '#cko-form-holder';
        var ckoPublicKey = '<?= $block->escapeHtml($block->config->getValue('public_key')); ?>';
        var paymentForm = document.getElementById('saveCardForm');
        var ckoTheme = '';

        // Initialize the embedded form
        Frames.init({
            publicKey: ckoPublicKey,
            containerSelector: cardFormContainerId,
            theme: ckoTheme,
            debugMode: '<?= $block->escapeHtml(($block->config->getValue('debug') && $block->config->getValue('console_logging'))); ?>',
            frameActivated: function () {
                saveCardButton.attr("disabled", true);
            },
            cardValidationChanged: function(event) {
                if (Frames.isCardValid()) {
                    saveCardButton.attr("disabled", false);
                    Frames.submitCard();
                    Frames.unblockFields();
                }
            },
            cardTokenised: function(event) {
                // Add the card token to the form
                Frames.addCardToken(paymentForm, event.data.cardToken);

                // Add the card token to the hidden input field
                cardTokenField.val(event.data.cardToken);
            }
        });

        // Add card form controls
        showFormButton.on('click touch', function (event) {
            $(cardFormContainerId).show();
            saveCardButton.show();
            showFormButton.hide();
        });

        // Handle the submit event
        saveCardButton.on('click touch', function (event) {
            // Disable the save button
            saveCardButton.attr("disabled", true);

            // Start the loader
            $('body').trigger('processStart');

            // Send the request
            $.ajax({
                type: 'POST',
                url: '<?= $block->escapeHtml($block->getUrl('checkout_com/account/savecard')); ?>',
                data: {cardToken: cardTokenField.val()},
                success: function (data) {
                    if (!data.success) {
                        // Todo - handle error message display
                        $('body').trigger('processStop');
                        //self.showMessage('error', data.message);
                    }
                    else if (data.success && data.url) {
                        // Todo - handle3 DS redirection
                        window.location.href = data.url
                    }
                },
                error: function (request, status, error) {
                   // Todo - handle error message display
                   $('body').trigger('processStop');
                   // self.showMessage('error', error);
                }
            });
        });
    });
</script>