<?php
/**
 * Checkout.com Magento 2 Payment module (https://www.checkout.com)
 *
 * Copyright (c) 2017 Checkout.com (https://www.checkout.com)
 * Author: David Fiaty | integration@checkout.com
 *
 * License GNU/GPL V3 https://www.gnu.org/licenses/gpl-3.0.en.html
 */
 
use Magento\Framework\View\Element\Template;
use Magento\Vault\Api\Data\PaymentTokenInterface;
use Magento\Vault\Block\CardRendererInterface;

/** @var CardRendererInterface|Template $block */

$ccNumberView = $block->escapeHtml($block->getNumberLast4Digits());
?>
<tr>
    <td data-th="<?= $block->escapeHtml(__('Card Number')) ?>" class="col card-number">
        <span><?= $block->escapeHtml(__('ending')); ?></span> <?= $ccNumberView ?>
    </td>
    <td data-th="<?= $block->escapeHtml(__('Expiration Date')) ?>" class="col card-expire">
        <?= $block->escapeHtml($block->getExpDate()); ?>
    </td>
    <td data-th="<?= $block->escapeHtml(__('Type')) ?>" class="col card-type">
        <img src="<?= $block->cardHandler->getCardIcon($block->getCartType()); ?>"
                style="display:inline-block; vertical-align:-50%"
        > <?= $this->cardHandler->getCardScheme($block->getCartType()) ?>
    </td>
    <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
        <form
            class="form"
            action="<?= $block->escapeUrl($block->getUrl('vault/cards/deleteaction')); ?>"
            method="post"
        >
            <?= $block->getBlockHtml('formkey')?>
            <input
                name="<?= PaymentTokenInterface::PUBLIC_HASH?>"
                value="<?= $block->getToken()->getPublicHash()?>"
                type="hidden"/>
            <button type="submit"
                    class="action delete"
                    data-mage-init='{
                                    "Magento_Vault/js/customer_account/deleteWidget":{
                                        "type": "popup",
                                        "modalClass": "my-credit-cards-popup",
                                        "toggleEvent": "click",
                                        "title": "<?= $block->escapeHtml(__('Delete')) ?>",
                                        "content": "Are you sure you want to delete this card: XXXX XXXX XXXX <?= $ccNumberView ?>?"
                                    }
                                }'>
                <span><?= $block->escapeHtml(__('Delete')) ?></span>
            </button>
        </form>
    </td>
</tr>