<?php
/**
 * Checkout.com
 * Authorized and regulated as an electronic money institution
 * by the UK Financial Conduct Authority (FCA) under number 900816.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Checkout.com
 * @author    Platforms Development Team <platforms@checkout.com>
 * @copyright 2010-present Checkout.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://docs.checkout.com/
 */

use Magento\Framework\Escaper;

/* @var Escaper $escaper */
?>

<div data-role="collapsible" id="<?= $escaper->escapeHtmlAttr($block->getData('apm_id')) ?>" class="cko-apm <?= $escaper->escapeHtmlAttr($block->getData('apm_id'))?>">
    <div data-role="trigger">
        <span class="bg-<?= $escaper->escapeHtmlAttr($block->getData('apm_id'))?> bg-apm"></span>
        <span><?= $escaper->escapeHtml($block->getData('title'))?></span>
    </div>
</div>
<div data-role="content" class="apm-content">
    <form id="cko-apm-form-<?= $escaper->escapeHtmlAttr($block->getData('apm_id'))?>">
        <input type="hidden" name="source" value="<?= $escaper->escapeHtmlAttr($block->getData('apm_id'))?>" required>
        <div class="input-group">
            <label class="icon" for="name">
            <span class="ckojs ckojs-card"></label>
            <input type="text" id="name" name="name" placeholder="<?= $escaper->escapeHtmlAttr(__('Name')); ?>" class="input-control" required>
        </div>
        <div class="input-group">
            <label class="icon" for="email">
                <span class="ckojs ckojs-card"></label>
            <input type="email" id="email" name="email" placeholder="<?= $escaper->escapeHtmlAttr(__('Email')); ?>" class="input-control" required>
        </div>
        <div class="input-group">
            <label class="icon" for="document">
            <span class="ckojs ckojs-card"></label>
            <input type="text" id="document" name="document" placeholder="<?= $escaper->escapeHtmlAttr(__('Cadastro de Pessoas Físicas or Cadastro Nacional da Pessoa Jurídica')); ?>" class="input-control" required>
        </div>
    </form>
</div>
