<?php
/**
 * Checkout.com
 * Authorized and regulated as an electronic money institution
 * by the UK Financial Conduct Authority (FCA) under number 900816.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Checkout.com
 * @author    Platforms Development Team <platforms@checkout.com>
 * @copyright 2010-present Checkout.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://docs.checkout.com/
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/**
 * @var Escaper $escaper
 * @var SecureHtmlRenderer $secureRenderer
 */
?>

<div data-role="collapsible" id="<?= $escaper->escapeHtmlAttr($block->getData('apm_id')) ?>"
     class="cko-apm <?= $escaper->escapeHtmlAttr($block->getData('apm_id')) ?>">
    <div data-role="trigger">
        <span class="bg-<?= $escaper->escapeHtmlAttr($block->getData('apm_id')) ?> bg-apm"></span>
        <span><?= $escaper->escapeHtml($block->getData('title')) ?></span>
    </div>
</div>
<div data-role="content" class="apm-content">
    <form id="cko-apm-form-<?= $escaper->escapeHtmlAttr($block->getData('apm_id')) ?>">
        <input type="hidden" name="source" value="<?= $escaper->escapeHtmlAttr($block->getData('apm_id')) ?>" required>
        <?php if ($block->getData('service_previous_mode')): ?>
            <div class="input-group">
                <label class="icon" for="bic">
                    <span class="ckojs ckojs-card"></label>
                <select name="bic" id="bic" required>
                    <option value=""><?= $escaper->escapeHtml(__('BIC')); ?></option>
                </select>
            </div>
        <?php endif; ?>
        <div class="input-group">
            <label class="icon" for="description">
                <span class="ckojs ckojs-card"></label>
            <input type="text" id="description" name="description" placeholder="<?= $escaper->escapeHtmlAttr(__('Description')); ?>" class="input-control"
                   required>
        </div>
        <br>
    </form>
</div>
