<?php
/**
 * Checkout.com
 * Authorized and regulated as an electronic money institution
 * by the UK Financial Conduct Authority (FCA) under number 900816.
 *
 * PHP version 8
 *
 * @category  Magento2
 * @package   Checkout.com
 * @author    Platforms Development Team <platforms@checkout.com>
 * @copyright 2010-present Checkout.com
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://docs.checkout.com/
 */
?>

<?php
if ($block->getViewModel()->isApplePayEnabledForAllBrowsers()):
?>
    <script type="text/x-magento-init">
        {
            "#ckoApplePayButton": {
                "CheckoutCom_Magento2/js/view/payment/cart/checkoutcom_applepay_cart": {
                    "type": "Cart",
                    "configName": "enabled_on_cart",
                    "allBrowsersSupported":true
                }
            }
        }
    </script>
    <script src="https://applepay.cdn-apple.com/jsapi/1.latest/apple-pay-sdk.js"></script>
    <apple-pay-button id="ckoApplePayButton" buttonstyle="black" type="plain" locale="en-US" class="apple-pay-button checkout ap-cart"></apple-pay-button>
<?php
else:
?>
    <script type="text/x-magento-init">
        {
            "#ckoApplePayButton": {
                "CheckoutCom_Magento2/js/view/payment/cart/checkoutcom_applepay_cart": {
                    "type": "Cart",
                    "configName": "enabled_on_cart"
                }
            }
        }
    </script>
    <div class="primary">
        <button id="ckoApplePayButton" type="button"  style="display: none" class="apple-pay-button action primary checkout ap-cart"></button>
    </div>
<?php
endif;
?>

