<?php
/**
 * Checkout.com
 * Authorized and regulated as an electronic money institution
 * by the UK Financial Conduct Authority (FCA) under number 900816.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Checkout.com
 * @author    Platforms Development Team <platforms@checkout.com>
 * @copyright 2010-present Checkout.com
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://docs.checkout.com/
 */
?>
<script type="text/x-magento-init">
	{"*": {"CheckoutCom_Magento2/js/view/payment/cart/checkoutcom_applepay_cart": {}}}
</script>
<div class="primary">
    <button id="ckoApplePayButton" type="button"  style="display: none" class="apple-pay-button action primary checkout ap-cart"></button>
</div>
