<fieldset class="admin__fieldset payment-method checkoutcom_moto" id="payment_form_checkoutcom_moto" style="display: none;">
    <br>
    <div id="cko-form-holder">
        <form id="saveCardForm" method="POST">
            <input type="hidden" id="ckoCardToken" name="ckoCardToken">
        </form>
    </div>
</fieldset>

<script type="text/javascript">
    require(['jquery', 'domReady!', 'framesjs'], function ($) {
        // Prepare the elements
        var cardTokenField = $('#ckoCardToken');
        var cardFormContainerId = '#cko-form-holder';
        var paymentForm = document.getElementById('saveCardForm');
        var ckoTheme = '';
        
        // Remove any existing event handlers
        Frames.removeAllEventHandlers(Frames.Events.CARD_VALIDATION_CHANGED);
        Frames.removeAllEventHandlers(Frames.Events.CARD_TOKENISED);
        Frames.removeAllEventHandlers(Frames.Events.FRAME_ACTIVATED);
            
        // Initialize the embedded form
        Frames.init({
            publicKey: '<?= $block->config->getMotoKeys()['public_key'] ?>',
            containerSelector: cardFormContainerId,
            theme: ckoTheme,
            debugMode: '<?= $block->config->getValue('debug') ?>',
            cardValidationChanged: function(event) {
                if (Frames.isCardValid()) {
                    Frames.submitCard();
                    Frames.unblockFields();
                }
            },
            cardTokenised: function(event) {                        
                // Add the card token to the hidden input field
                cardTokenField.val(event.data.cardToken);
            }
        });  
    });
</script>