<fieldset class="admin__fieldset payment-method checkoutcom_moto" id="payment_form_checkoutcom_moto" style="display: none;">
    <div class="card-form-container">
        <form class="widget-container" id="saveCardForm" method="POST">
            <?php echo $block->getBlockHtml('formkey')?>
            <input type="hidden" id="cko-card-token" name="cko-card-token">
        </form>
    </div>

    <script type="text/javascript">
    require(['jquery', 'domReady!', 'framesjs'], function ($) {
        // Prepare the elements
        var saveCardButton = $('#cko-save-card');
        var showFormButton = $('#cko-show-card-form');
        var cardTokenField = $('#cko-card-token');
        var cardFormContainerId = '#cko-form-holder';
        var ckoPublicKey = '<?= $block->config->getValue('public_key'); ?>';
        var paymentForm = document.getElementById('saveCardForm');
        var ckoTheme = '';
        
        // Todo - Connect the  debug mode to config
        var ckoDebugMode = false;

        // Initialize the embedded form
        Frames.init({
            publicKey: ckoPublicKey,
            containerSelector: cardFormContainerId,
            theme: ckoTheme,
            debugMode: ckoDebugMode,
            frameActivated: function () {
                saveCardButton.attr("disabled", true);
            },
            cardValidationChanged: function(event) {
                if (Frames.isCardValid()) {
                    saveCardButton.attr("disabled", false);
                    Frames.submitCard();
                    Frames.unblockFields();
                }
            },
            cardTokenised: function(event) {                        
                // Add the card token to the form
                Frames.addCardToken(paymentForm, event.data.cardToken);

                // Add the card token to the hidden input field
                cardTokenField.val(event.data.cardToken);
            }
        });  

        // Add card form controls
        showFormButton.on('click touch', function (event) {
            $(cardFormContainerId).show();
            saveCardButton.show();
            showFormButton.hide();
        });

        // Handle the submit event
        saveCardButton.on('click touch', function (event) {
            // Disable the save button
            saveCardButton.attr("disabled", true);

            // Prevent default events
            event.preventDefault();

            // Send the request
            $.ajax({
                type: 'POST',
                url: '<?= $block->getUrl('checkout_com/account/savecard'); ?>',
                data: {cardToken: cardTokenField.val()},
                success: function (data) {
                    if (!data.success) {
                        //FullScreenLoader.stopLoader();
                        //self.showMessage('error', data.message);
                    }
                    else if (data.success && data.url) {
                        // Handle 3DS redirection
                        //window.location.href = data.url
                    }
                    else {
                        // Normal redirection
                        //RedirectOnSuccessAction.execute();
                    }
                },
                error: function (request, status, error) {
                    //FullScreenLoader.stopLoader();
                   // self.showMessage('error', error);
                }
            });
        });
    });
    </script>
</fieldset>