<?php
/**
 * Checkout.com
 * Authorized and regulated as an electronic money institution
 * by the UK Financial Conduct Authority (FCA) under number 900816.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Checkout.com
 * @author    Platforms Development Team <platforms@checkout.com>
 * @copyright 2010-present Checkout.com
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://docs.checkout.com/
 */

/**
 * @var PaymentMethod $block
 * @var Escaper $escaper
 */

use CheckoutCom\Magento2\Block\Paypal\Review\PaymentMethod;
use Magento\Framework\Escaper;

?>
<div class="box box-order-billing-address">
    <strong class="box-title"><span><?= $escaper->escapeHtml(__('Payment Method')) ?></span></strong>
    <div class="box-content">
        <?= $escaper->escapeHtml($block->getPaymentMethod()); ?><br>
        <?= $escaper->escapeHtml($block->getEmail()); ?>
    </div>
</div>
