<?php
/**
 * @var PlaceOrderButton $block
 * @var Escaper $escaper
 */

use CheckoutCom\Magento2\Block\Paypal\Review\PlaceOrderButton;
use Magento\Framework\Escaper;

?>
<?php // Do not change this id ?>
<div id="checkoutcom_paypal_container"
      class="form order-review-form">
    <div class="message message-cko"></div>
    <div class="message message-response-code"></div>
    <div class="message debug-message"></div>
    <?= $block->getChildHtml('agreements') ?>
    <div class="actions-toolbar" id="review-buttons-container">
        <div class="primary">
            <button type="button" id="review-button" <?php if (!$block->canPlaceOrder()): ?>disabled<?php endif; ?>
                    class="action checkout primary"
                    value="<?= $escaper->escapeHtml(__('Place Order')) ?>">
                <span><?= $escaper->escapeHtml(__('Place Order')) ?></span>
            </button>
        </div>
        <span class="please-wait load indicator" id="review-please-wait"
              data-text="<?= $escaper->escapeHtml(__('Submitting order information...')) ?>">
                   <span><?= $escaper->escapeHtml(__('Submitting order information...')) ?></span>
                </span>
        <?= /* @noEscape */
        $secureRenderer->renderStyleAsTag("display: none;", 'span#review-please-wait') ?>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "#checkoutcom_paypal_container": {
            "CheckoutCom_Magento2/js/view/payment/method-renderer/checkoutcom_paypal_review": {
                "chkPayPalContextId": "<?= $escaper->escapeJs($block->getContextId()); ?>",
                "methodId": "<?= $escaper->escapeJs($block->getPaymentMethod()); ?>",
                "buttonSelector": "#review-button"
            }
        }
    }


</script>
