<?php
/**
 * Checkout.com
 * Authorized and regulated as an electronic money institution
 * by the UK Financial Conduct Authority (FCA) under number 900816.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Checkout.com
 * @author    Platforms Development Team <platforms@checkout.com>
 * @copyright 2010-present Checkout.com
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://docs.checkout.com/
 */

/**
 * @var PlaceOrderButton $block
 * @var Escaper $escaper
 * @var SecureHtmlRenderer $secureRenderer
 */

use CheckoutCom\Magento2\Block\Paypal\Review\PlaceOrderButton;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

?>

<div class="form order-review-form" id="checkoutcom_paypal_container">
    <div class="message message-cko"></div>
    <div class="message message-response-code"></div>
    <div class="message debug-message"></div>
    <?= $block->getChildHtml('agreements') ?>
    <div class="actions-toolbar" id="review-buttons-container">
        <div class="primary">
            <button type="button" id="review-button" <?php if (!$block->canPlaceOrder()): ?>disabled<?php endif; ?>
                    class="action checkout primary"
                    value="<?= $escaper->escapeHtml(__('Place Order')) ?>">
                <span><?= $escaper->escapeHtml(__('Place Order')) ?></span>
            </button>
        </div>
        <span class="please-wait load indicator" id="review-please-wait"
              data-text="<?= $escaper->escapeHtmlAttr(__('Submitting order information...')) ?>">
           <span><?= $escaper->escapeHtml(__('Submitting order information...')) ?></span>
        </span>
        <?= /* @noEscape */
        $secureRenderer->renderStyleAsTag("display: none;", 'span#review-please-wait') ?>
    </div>
</div>
<?php
$data = [
    "#checkoutcom-paypal-container" => [
        "CheckoutCom_Magento2/js/view/payment/method-renderer/checkoutcom_paypal_review" => [
            "chkPayPalContextId" => $block->getContextId(),
            "addressForm" => ".form-address-edit",
            "methodId" => $block->getPaymentMethod(),
            "buttonSelector" => "#review-button"
        ]
    ]
];

$jsonInit = json_encode($data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
?>

<?= /* @noEscape */ $secureRenderer->renderTag(
    'script',
    ['type' => 'text/x-magento-init'],
    $jsonInit,
    false
) ?>
