<?php
/**
 * Checkout.com
 * Authorized and regulated as an electronic money institution
 * by the UK Financial Conduct Authority (FCA) under number 900816.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Checkout.com
 * @author    Platforms Development Team <platforms@checkout.com>
 * @copyright 2010-present Checkout.com
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://docs.checkout.com/
 */

/**
 * @var ShippinAddress $block
 * @var Escaper $escaper
 */

use CheckoutCom\Magento2\Block\Paypal\Review\ShippinAddress;
use Magento\Framework\Escaper;

?>

<div class="box box-order-shipping-address">
    <strong class="box-title">
        <span><?= $escaper->escapeHtml(__('Shipping Address')) ?></span>
    </strong>
    <div class="box-content">
        <form class="form-address-edit"
              action="https://nas.checmag2.dnd.fr/customer/address/formPost/" method="post" id="form-validate" enctype="multipart/form-data"
              data-hasrequired="* Required Fields" novalidate="novalidate">
            <fieldset class="fieldset">
                <legend class="legend"><span>Contact Information</span></legend>
                <br>
                <input name="form_key" type="hidden" value="UITMiYzYJQuHSuqT"> <input type="hidden" name="success_url" value="">
                <input type="hidden" name="error_url" value="">

                <div class="field field-name-firstname required">
                    <label class="label" for="firstname"><span>First Name</span></label>
                    <div class="control">
                        <input type="text" id="firstname" name="firstname" value="SRDFSD" title="First Name" class="input-text required-entry"
                               data-validate="{required:true}" aria-required="true">
                    </div>
                </div>
                <div class="field field-name-lastname required">
                    <label class="label" for="lastname"><span>Last Name</span></label>
                    <div class="control">
                        <input type="text" id="lastname" name="lastname" value="FGDSF" title="Last Name" class="input-text required-entry"
                               data-validate="{required:true}" aria-required="true">
                    </div>
                </div>

                <div class="field company ">
                    <label class="label" for="company"><span>Company</span></label>
                    <div class="control">
                        <input type="text" name="company" id="company" title="Company" value="" class="input-text ">
                    </div>
                </div>
                <div class="field telephone required">
                    <label class="label" for="telephone"><span>Phone Number</span></label>
                    <div class="control">
                        <input type="text" name="telephone" value="" title="Phone Number" class="input-text required-entry" id="telephone" aria-required="true">
                    </div>
                </div>
            </fieldset>
            <fieldset class="fieldset">
                <legend class="legend"><span>Address</span></legend>
                <br>
                <div class="field street required">
                    <label for="street_1" class="label">
                        <span>Street Address</span>
                    </label>
                    <div class="control">
                        <div class="field primary">
                            <label for="street_1" class="label">
                        <span>
                            Street Address: Line 1                        </span>
                            </label>
                        </div>
                        <input type="text" name="street[0]" value="" title="Street Address" id="street_1" class="input-text required-entry"
                               aria-required="true">
                        <div class="nested">
                            <div class="field additional">
                                <label class="label" for="street_2">
                                    <span>Street Address: Line 2</span>
                                </label>
                                <div class="control">
                                    <input type="text" name="street[2]" value="" title="Street Address 2" id="street_2" class="input-text "
                                           aria-required="true">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="field city required">
                    <label class="label" for="city">
                        <span>City</span>
                    </label>
                    <div class="control">
                        <input type="text" name="city" value="" title="City" class="input-text required-entry" id="city" aria-required="true">
                    </div>
                </div>
                <div class="field region required">
                    <label class="label" for="region_id">
                        <span>State/Province</span>
                    </label>
                    <div class="control">
                        <select id="region_id" name="region_id" title="State/Province" class="validate-select region_id required-entry" aria-required="true"
                                defaultvalue="0" style="display: inline-block;">
                            <option value="">
                                Please select a region, state or province.
                            </option>
                            <option value="1">Alabama</option>
                            <option value="2">Alaska</option>
                            <option value="3">American Samoa</option>
                            <option value="4">Arizona</option>
                            <option value="5">Arkansas</option>
                            <option value="6">Armed Forces Africa</option>
                            <option value="7">Armed Forces Americas</option>
                            <option value="8">Armed Forces Canada</option>
                            <option value="9">Armed Forces Europe</option>
                            <option value="10">Armed Forces Middle East</option>
                            <option value="11">Armed Forces Pacific</option>
                            <option value="12">California</option>
                            <option value="13">Colorado</option>
                            <option value="14">Connecticut</option>
                            <option value="15">Delaware</option>
                            <option value="16">District of Columbia</option>
                            <option value="17">Federated States Of Micronesia</option>
                            <option value="18">Florida</option>
                            <option value="19">Georgia</option>
                            <option value="20">Guam</option>
                            <option value="21">Hawaii</option>
                            <option value="22">Idaho</option>
                            <option value="23">Illinois</option>
                            <option value="24">Indiana</option>
                            <option value="25">Iowa</option>
                            <option value="26">Kansas</option>
                            <option value="27">Kentucky</option>
                            <option value="28">Louisiana</option>
                            <option value="29">Maine</option>
                            <option value="30">Marshall Islands</option>
                            <option value="31">Maryland</option>
                            <option value="32">Massachusetts</option>
                            <option value="33">Michigan</option>
                            <option value="34">Minnesota</option>
                            <option value="35">Mississippi</option>
                            <option value="36">Missouri</option>
                            <option value="37">Montana</option>
                            <option value="38">Nebraska</option>
                            <option value="39">Nevada</option>
                            <option value="40">New Hampshire</option>
                            <option value="41">New Jersey</option>
                            <option value="42">New Mexico</option>
                            <option value="43">New York</option>
                            <option value="44">North Carolina</option>
                            <option value="45">North Dakota</option>
                            <option value="46">Northern Mariana Islands</option>
                            <option value="47">Ohio</option>
                            <option value="48">Oklahoma</option>
                            <option value="49">Oregon</option>
                            <option value="50">Palau</option>
                            <option value="51">Pennsylvania</option>
                            <option value="52">Puerto Rico</option>
                            <option value="53">Rhode Island</option>
                            <option value="54">South Carolina</option>
                            <option value="55">South Dakota</option>
                            <option value="56">Tennessee</option>
                            <option value="57">Texas</option>
                            <option value="58">Utah</option>
                            <option value="59">Vermont</option>
                            <option value="60">Virgin Islands</option>
                            <option value="61">Virginia</option>
                            <option value="62">Washington</option>
                            <option value="63">West Virginia</option>
                            <option value="64">Wisconsin</option>
                            <option value="65">Wyoming</option>
                        </select>
                        <input type="text" id="region" name="region" value="" title="State/Province" class="input-text" aria-required="true"
                               style="display: none;">
                    </div>
                </div>
                <div class="field zip required">
                    <label class="label" for="zip">
                        <span>Zip/Postal Code</span>
                    </label>
                    <div class="control">
                        <input type="text" name="postcode" value="" title="Zip/Postal Code" id="zip"
                               class="input-text validate-zip-international required-entry" aria-required="true">
                        <div role="alert" class="message warning">
                            <span></span>
                        </div>
                        <style>div.zip .message.warning {
                            display: none;
                        }</style>
                    </div>
                </div>
                <div class="field country required">
                    <label class="label" for="country">
                        <span>Country</span>
                    </label>
                    <div class="control">
                        <select name="country_id" id="country" class="required-entry" title="Country" data-validate="{'validate-select':true}"
                                aria-required="true">
                            <option value=""></option>
                            <option value="AF">Afghanistan</option>
                            <option value="AL">Albania</option>
                            <option value="DZ">Algeria</option>
                            <option value="AS">American Samoa</option>
                            <option value="AD">Andorra</option>
                            <option value="AO">Angola</option>
                            <option value="AI">Anguilla</option>
                            <option value="AQ">Antarctica</option>
                            <option value="AG">Antigua &amp; Barbuda</option>
                            <option value="AR">Argentina</option>
                            <option value="AM">Armenia</option>
                            <option value="AW">Aruba</option>
                            <option value="AU">Australia</option>
                            <option value="AT">Austria</option>
                            <option value="AZ">Azerbaijan</option>
                            <option value="BS">Bahamas</option>
                            <option value="BH">Bahrain</option>
                            <option value="BD">Bangladesh</option>
                            <option value="BB">Barbados</option>
                            <option value="BY">Belarus</option>
                            <option value="BE">Belgium</option>
                            <option value="BZ">Belize</option>
                            <option value="BJ">Benin</option>
                            <option value="BM">Bermuda</option>
                            <option value="BT">Bhutan</option>
                            <option value="BO">Bolivia</option>
                            <option value="BA">Bosnia &amp; Herzegovina</option>
                            <option value="BW">Botswana</option>
                            <option value="BV">Bouvet Island</option>
                            <option value="BR">Brazil</option>
                            <option value="IO">British Indian Ocean Territory</option>
                            <option value="VG">British Virgin Islands</option>
                            <option value="BN">Brunei</option>
                            <option value="BG">Bulgaria</option>
                            <option value="BF">Burkina Faso</option>
                            <option value="BI">Burundi</option>
                            <option value="KH">Cambodia</option>
                            <option value="CM">Cameroon</option>
                            <option value="CA">Canada</option>
                            <option value="CV">Cape Verde</option>
                            <option value="BQ">Caribbean Netherlands</option>
                            <option value="KY">Cayman Islands</option>
                            <option value="CF">Central African Republic</option>
                            <option value="TD">Chad</option>
                            <option value="CL">Chile</option>
                            <option value="CN">China</option>
                            <option value="CX">Christmas Island</option>
                            <option value="CC">Cocos (Keeling) Islands</option>
                            <option value="CO">Colombia</option>
                            <option value="KM">Comoros</option>
                            <option value="CG">Congo - Brazzaville</option>
                            <option value="CD">Congo - Kinshasa</option>
                            <option value="CK">Cook Islands</option>
                            <option value="CR">Costa Rica</option>
                            <option value="HR">Croatia</option>
                            <option value="CU">Cuba</option>
                            <option value="CW">Curaçao</option>
                            <option value="CY">Cyprus</option>
                            <option value="CZ">Czechia</option>
                            <option value="CI">Côte d’Ivoire</option>
                            <option value="DK">Denmark</option>
                            <option value="DJ">Djibouti</option>
                            <option value="DM">Dominica</option>
                            <option value="DO">Dominican Republic</option>
                            <option value="EC">Ecuador</option>
                            <option value="EG">Egypt</option>
                            <option value="SV">El Salvador</option>
                            <option value="GQ">Equatorial Guinea</option>
                            <option value="ER">Eritrea</option>
                            <option value="EE">Estonia</option>
                            <option value="SZ">Eswatini</option>
                            <option value="ET">Ethiopia</option>
                            <option value="FK">Falkland Islands</option>
                            <option value="FO">Faroe Islands</option>
                            <option value="FJ">Fiji</option>
                            <option value="FI">Finland</option>
                            <option value="FR">France</option>
                            <option value="GF">French Guiana</option>
                            <option value="PF">French Polynesia</option>
                            <option value="TF">French Southern Territories</option>
                            <option value="GA">Gabon</option>
                            <option value="GM">Gambia</option>
                            <option value="GE">Georgia</option>
                            <option value="DE">Germany</option>
                            <option value="GH">Ghana</option>
                            <option value="GI">Gibraltar</option>
                            <option value="GR">Greece</option>
                            <option value="GL">Greenland</option>
                            <option value="GD">Grenada</option>
                            <option value="GP">Guadeloupe</option>
                            <option value="GU">Guam</option>
                            <option value="GT">Guatemala</option>
                            <option value="GG">Guernsey</option>
                            <option value="GN">Guinea</option>
                            <option value="GW">Guinea-Bissau</option>
                            <option value="GY">Guyana</option>
                            <option value="HT">Haiti</option>
                            <option value="HM">Heard &amp; McDonald Islands</option>
                            <option value="HN">Honduras</option>
                            <option value="HK">Hong Kong SAR China</option>
                            <option value="HU">Hungary</option>
                            <option value="IS">Iceland</option>
                            <option value="IN">India</option>
                            <option value="ID">Indonesia</option>
                            <option value="IR">Iran</option>
                            <option value="IQ">Iraq</option>
                            <option value="IE">Ireland</option>
                            <option value="IM">Isle of Man</option>
                            <option value="IL">Israel</option>
                            <option value="IT">Italy</option>
                            <option value="JM">Jamaica</option>
                            <option value="JP">Japan</option>
                            <option value="JE">Jersey</option>
                            <option value="JO">Jordan</option>
                            <option value="KZ">Kazakhstan</option>
                            <option value="KE">Kenya</option>
                            <option value="KI">Kiribati</option>
                            <option value="XK">Kosovo</option>
                            <option value="KW">Kuwait</option>
                            <option value="KG">Kyrgyzstan</option>
                            <option value="LA">Laos</option>
                            <option value="LV">Latvia</option>
                            <option value="LB">Lebanon</option>
                            <option value="LS">Lesotho</option>
                            <option value="LR">Liberia</option>
                            <option value="LY">Libya</option>
                            <option value="LI">Liechtenstein</option>
                            <option value="LT">Lithuania</option>
                            <option value="LU">Luxembourg</option>
                            <option value="MO">Macao SAR China</option>
                            <option value="MG">Madagascar</option>
                            <option value="MW">Malawi</option>
                            <option value="MY">Malaysia</option>
                            <option value="MV">Maldives</option>
                            <option value="ML">Mali</option>
                            <option value="MT">Malta</option>
                            <option value="MH">Marshall Islands</option>
                            <option value="MQ">Martinique</option>
                            <option value="MR">Mauritania</option>
                            <option value="MU">Mauritius</option>
                            <option value="YT">Mayotte</option>
                            <option value="MX">Mexico</option>
                            <option value="FM">Micronesia</option>
                            <option value="MD">Moldova</option>
                            <option value="MC">Monaco</option>
                            <option value="MN">Mongolia</option>
                            <option value="ME">Montenegro</option>
                            <option value="MS">Montserrat</option>
                            <option value="MA">Morocco</option>
                            <option value="MZ">Mozambique</option>
                            <option value="MM">Myanmar (Burma)</option>
                            <option value="NA">Namibia</option>
                            <option value="NR">Nauru</option>
                            <option value="NP">Nepal</option>
                            <option value="NL">Netherlands</option>
                            <option value="NC">New Caledonia</option>
                            <option value="NZ">New Zealand</option>
                            <option value="NI">Nicaragua</option>
                            <option value="NE">Niger</option>
                            <option value="NG">Nigeria</option>
                            <option value="NU">Niue</option>
                            <option value="NF">Norfolk Island</option>
                            <option value="KP">North Korea</option>
                            <option value="MK">North Macedonia</option>
                            <option value="MP">Northern Mariana Islands</option>
                            <option value="NO">Norway</option>
                            <option value="OM">Oman</option>
                            <option value="PK">Pakistan</option>
                            <option value="PW">Palau</option>
                            <option value="PS">Palestinian Territories</option>
                            <option value="PA">Panama</option>
                            <option value="PG">Papua New Guinea</option>
                            <option value="PY">Paraguay</option>
                            <option value="PE">Peru</option>
                            <option value="PH">Philippines</option>
                            <option value="PN">Pitcairn Islands</option>
                            <option value="PL">Poland</option>
                            <option value="PT">Portugal</option>
                            <option value="QA">Qatar</option>
                            <option value="RO">Romania</option>
                            <option value="RU">Russia</option>
                            <option value="RW">Rwanda</option>
                            <option value="RE">Réunion</option>
                            <option value="WS">Samoa</option>
                            <option value="SM">San Marino</option>
                            <option value="SA">Saudi Arabia</option>
                            <option value="SN">Senegal</option>
                            <option value="RS">Serbia</option>
                            <option value="SC">Seychelles</option>
                            <option value="SL">Sierra Leone</option>
                            <option value="SG">Singapore</option>
                            <option value="SX">Sint Maarten</option>
                            <option value="SK">Slovakia</option>
                            <option value="SI">Slovenia</option>
                            <option value="SB">Solomon Islands</option>
                            <option value="SO">Somalia</option>
                            <option value="ZA">South Africa</option>
                            <option value="GS">South Georgia &amp; South Sandwich Islands</option>
                            <option value="KR">South Korea</option>
                            <option value="ES">Spain</option>
                            <option value="LK">Sri Lanka</option>
                            <option value="BL">St. Barthélemy</option>
                            <option value="SH">St. Helena</option>
                            <option value="KN">St. Kitts &amp; Nevis</option>
                            <option value="LC">St. Lucia</option>
                            <option value="MF">St. Martin</option>
                            <option value="PM">St. Pierre &amp; Miquelon</option>
                            <option value="VC">St. Vincent &amp; Grenadines</option>
                            <option value="SD">Sudan</option>
                            <option value="SR">Suriname</option>
                            <option value="SJ">Svalbard &amp; Jan Mayen</option>
                            <option value="SE">Sweden</option>
                            <option value="CH">Switzerland</option>
                            <option value="SY">Syria</option>
                            <option value="ST">São Tomé &amp; Príncipe</option>
                            <option value="TW">Taiwan, Province of China</option>
                            <option value="TJ">Tajikistan</option>
                            <option value="TZ">Tanzania</option>
                            <option value="TH">Thailand</option>
                            <option value="TL">Timor-Leste</option>
                            <option value="TG">Togo</option>
                            <option value="TK">Tokelau</option>
                            <option value="TO">Tonga</option>
                            <option value="TT">Trinidad &amp; Tobago</option>
                            <option value="TN">Tunisia</option>
                            <option value="TR">Turkey</option>
                            <option value="TM">Turkmenistan</option>
                            <option value="TC">Turks &amp; Caicos Islands</option>
                            <option value="TV">Tuvalu</option>
                            <option value="UM">U.S. Outlying Islands</option>
                            <option value="VI">U.S. Virgin Islands</option>
                            <option value="UG">Uganda</option>
                            <option value="UA">Ukraine</option>
                            <option value="AE">United Arab Emirates</option>
                            <option value="GB">United Kingdom</option>
                            <option value="US" selected="selected">United States</option>
                            <option value="UY">Uruguay</option>
                            <option value="UZ">Uzbekistan</option>
                            <option value="VU">Vanuatu</option>
                            <option value="VA">Vatican City</option>
                            <option value="VE">Venezuela</option>
                            <option value="VN">Vietnam</option>
                            <option value="WF">Wallis &amp; Futuna</option>
                            <option value="EH">Western Sahara</option>
                            <option value="YE">Yemen</option>
                            <option value="ZM">Zambia</option>
                            <option value="ZW">Zimbabwe</option>
                            <option value="AX">Åland Islands</option>
                        </select></div>
                </div>

                <input type="hidden" name="default_billing" value="1">
                <input type="hidden" name="default_shipping" value="1">
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" data-action="save-address" title="Save Address">
                        <span>Save Address</span>
                    </button>
                </div>
            </div>
        </form>

        <address>
            <?= $escaper->escapeHtml(
                $block->renderAddress(),
                ['br']
            ); ?>
        </address>
    </div>
</div>
