<?php
/**
 * Checkout.com
 * Authorized and regulated as an electronic money institution
 * by the UK Financial Conduct Authority (FCA) under number 900816.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Checkout.com
 * @author    Platforms Development Team <platforms@checkout.com>
 * @copyright 2010-present Checkout.com
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://docs.checkout.com/
 */

use CheckoutCom\Magento2\Block\Paypal\Script;
use Magento\Framework\Escaper;
/** @var Escaper $escaper */
/** @var Script $block */
$clientId = $block->getClientId();
$partnerId = $block->getPartnerAttributionId();
$paypalMerchantId = $block->getPaypalMerchantId();
if ($clientId && $partnerId && $paypalMerchantId):
?>
<script>
    window.paypalCheckoutConfig = {
        intent: '<?= $escaper->escapeJs($block->getIntent()) ?>',
        commit: '<?= $escaper->escapeJs($block->getCommit()); ?>',
        pageType: '<?= $escaper->escapeUrl($block->getPageType()) ?>'
    }
</script>
<?php endif; ?>
