<?php
/**
 * Checkout.com Magento 2 Payment module (https://www.checkout.com)
 *
 * Copyright (c) 2017 Checkout.com (https://www.checkout.com)
 * Author: David Fiaty | integration@checkout.com
 *
 * License GNU/GPL V3 https://www.gnu.org/licenses/gpl-3.0.en.html
 */

use Magento\Vault\Model\Ui\TokenUiComponentProviderInterface;

/** @var \Magento\Framework\View\Element\Template $block */
$details    = $block->getData(TokenUiComponentProviderInterface::COMPONENT_DETAILS);
$icon       = $block->getData('icons')[$details['type']];
$id         = $block->escapeHtml($block->getData('id'));

?>

<div data-mage-init='{
        "CheckoutCom_Magento2/js/vault": {
            "container": "payment_<?php /* @noEscape */ echo $id; ?>",
            "publicHash": "<?php echo $block->escapeHtml($block->getData(TokenUiComponentProviderInterface::COMPONENT_PUBLIC_HASH)); ?>",
            "code": "<?php echo $block->escapeHtml($block->getData('code')); ?>"
        }
    }' id="payment_<?php /* @noEscape */ echo $id;?>" class="admin__field">
    <div class="admin__field-control control">
        <input type="radio" id="token_switcher_<?php /* @noEscape */ echo $id; ?>" name="payment[token_switcher]"/>
        <img src="<?php echo $block->escapeUrl($icon['url']); ?>"
             width="<?php echo $block->escapeHtml($icon['width']); ?>"
             height="<?php echo $block->escapeHtml($icon['height']); ?>"
             class="payment-icon" >
        <span><?php echo $block->escapeHtml(__('ending'));?></span>
        <span><?php echo $block->escapeHtml($details['maskedCC']); ?></span>
        (<span><?php echo $block->escapeHtml(__('expires'));?></span>:
        <span><?php echo $block->escapeHtml($details['expirationDate']); ?></span>)
    </div>
</div>
