<?php

/**
 * Checkout.com
 * Authorized and regulated as an electronic money institution
 * by the UK Financial Conduct Authority (FCA) under number 900816.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Checkout.com
 * @author    Platforms Development Team <platforms@checkout.com>
 * @copyright 2010-present Checkout.com
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://docs.checkout.com/
 */

use CheckoutCom\Magento2\Block\Adminhtml\System\Config\Field\LogFiles;

/** @var LogFiles $block */

?>
<?php echo $block->getElementHtml(); ?>
<?php echo $block->getButtonHtml($block->getButtonUrl()); ?>
