<?php

/**
 * Checkout.com
 * Authorized and regulated as an electronic money institution
 * by the UK Financial Conduct Authority (FCA) under number 900816.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Checkout.com
 * @author    Platforms Development Team <platforms@checkout.com>
 * @copyright 2010-present Checkout.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://docs.checkout.com/
 */

use CheckoutCom\Magento2\Block\Adminhtml\System\Config\Field\AbstractCallbackUrl;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/**
 * @var AbstractCallbackUrl $block
 * @var Escaper $escaper
 * @var SecureHtmlRenderer $secureRenderer
 */
?>

<?= $escaper->escapeHtml($block->getElementHtml()); ?>

<div id="webhook_nas" style="display: <?= ($block->getHidden() === true) ? 'none' : 'block' ?> ">
    <span id="webhook_span_nas">
        <br>
        <p> <?= $escaper->escapeHtml(__('In order to set your webhook, please follow these steps:')) ?></p>
        <br>
        <p> <?= $escaper->escapeHtml(__('1- Create your Notification in Checkout Dashboard: ')) ?> <a
                href="https://www.checkout.com/docs/four/dashboard/notifications#Create_a_notification" target="_blank"><?= $escaper->escapeHtml(__('Notifications - Docs')) ?></a></p>
        <p><?= $escaper->escapeHtml(__('2- Select all the events in the Notification')) ?></p>
        <p><?= $escaper->escapeHtml(__('3- Fill the Notification URL from Magento "Webhook URL"')) ?></p>
        <p><?= $escaper->escapeHtml(__(
                '4- Finally, copy the Authorization Header Key from your Notification into the "Authorization Header Key" field in Magento and save the configuration'
            )) ?></p>
        </span>
</div>
