<?php
/**
 * Checkout.com
 * Authorized and regulated as an electronic money institution
 * by the UK Financial Conduct Authority (FCA) under number 900816.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Checkout.com
 * @author    Platforms Development Team <platforms@checkout.com>
 * @copyright 2010-present Checkout.com
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://docs.checkout.com/
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/**
 * @var SecureHtmlRenderer $secureRenderer
 * @var Template $block
 * @var Escaper $escaper
 */

?>

<?php
if ($block->getViewModel()->isApplePayEnabledForAllBrowsers()):
    $script = json_encode([
        "#ckoApplePayButton" => [
            "CheckoutCom_Magento2/js/frames/view/payment/cart/checkoutcom_applepay_cart" => [
                "type" => "Cart",
                "configName" => "enabled_on_cart",
                "allBrowsersSupported" => true,
            ],
        ],
    ], JSON_UNESCAPED_SLASHES);

    ?>
    <?= $secureRenderer->renderTag(
    'script',
    ['type' => 'text/x-magento-init'],
    $script,
    false
); ?>

    <apple-pay-button id="ckoApplePayButton" buttonstyle="black" type="plain" locale="en-US" class="apple-pay-button checkout ap-cart"></apple-pay-button>
<?php
else:
    $script = json_encode([
        "#ckoApplePayButton" => [
            "CheckoutCom_Magento2/js/frames/view/payment/cart/checkoutcom_applepay_cart" => [
                "type" => "Cart",
                "configName" => "enabled_on_cart",
            ],
        ],
    ], JSON_UNESCAPED_SLASHES);
    ?>
    <?= $secureRenderer->renderTag(
    'script',
    ['type' => 'text/x-magento-init'],
    $script,
    false
); ?>
    <div class="primary">
        <button id="ckoApplePayButton" type="button" style="display: none" class="apple-pay-button action primary checkout ap-cart"></button>
    </div>
<?php
endif;
?>

