<?php
/**
 * Checkout.com
 * Authorized and regulated as an electronic money institution
 * by the UK Financial Conduct Authority (FCA) under number 900816.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Checkout.com
 * @author    Platforms Development Team <platforms@checkout.com>
 * @copyright 2010-present Checkout.com all rights reserved
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://docs.checkout.com/
 */
?>
<?php
$jsLayout = $block->getJsLayout();

$script = <<<script
{
    "#paypal-express-button-container": {
        "Magento_Ui/js/core/app": {$jsLayout}
    }
}
script;
?>

<?= /* @noEscape */ $secureRenderer->renderTag(
    'script',
    ['type' => 'text/x-magento-init'],
    $script,
    false
); ?>

<div id="paypal-express-button-container"
     data-bind="scope: 'paypal_express_button'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
