<?php
/**
 * Checkout.com
 * Authorized and regulated as an electronic money institution
 * by the UK Financial Conduct Authority (FCA) under number 900816.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Checkout.com
 * @author    Platforms Development Team <platforms@checkout.com>
 * @copyright 2010-2019 Checkout.com
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://docs.checkout.com/
 */
?>

<?php

/**
 * Checkout.com
 * Authorized and regulated as an electronic money institution
 * by the UK Financial Conduct Authority (FCA) under number 900816.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Checkout.com
 * @author    Platforms Development Team <platforms@checkout.com>
 * @copyright 2010-2019 Checkout.com
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://docs.checkout.com/
 */

$card = $block->getData('card');
$details = json_decode($card->getTokenDetails() ?: '{}', true);

?>
<div id="cko-vault-card-<?= $block->escapeHtmlAttr($card->getEntityId())?>" class="cko-vault-card">
    <div class="vault-details">
        <label>
            <input type="radio" name="publicHash" value="<?= $block->escapeHtmlAttr($card->getPublicHash())?>">
            <img src="<?= $block->escapeHtmlAttr($block->cardHandler->getCardIcon($details['type'])); ?>"
                style="display:inline-block; vertical-align:-50%"
            >
        </label>
        <span>
            <?= $block->escapeHtml($block->vaultHandler->renderTokenData($card))?>
        </span>
    </div>
    <?php
    if ($block->config->getValue('require_cvv', 'checkoutcom_vault')): ?>
        <div class="vault-cvv">
            <input type="text" name="cvv" maxlength="4" placeholder="<?= $block->escapeHtmlAttr(__('CVV')) ?>">
        </div>
    <?php endif; ?>
    <div class="clr"></div>
</div>