<?php
$card = $block->getData('card');
$details = json_decode($card->getTokenDetails() ?: '{}', true);

?>
<div id="cko-vault-card-<?= $card->getEntityId()?>" class="cko-vault-card" tabindex="<?= $block->getData('tabIndex')?>">
    <div class="vault-details">
        <label>
            <input type="radio" name="savedCard" value="<?= $card->getPublicHash()?>">
            <img src="<?php /* @noEscape */ echo $block->cardHandler->getCardIcon($details['type']); ?>"
                style="display:inline-block; vertical-align:-50%"
            >
        </label>
        <span>
            <?= $block->vaultHandler->renderTokenData($card)?>
        </span>
    </div>
    <?php if ($block->config->getValue('cvv_required')): ?>
        <div class="vault-cvv">
            <input type="text" name="cvv" maxlength="4">
        </div>
    <?php endif; ?>
    <div class="clr"></div>
</div>