<?php

/**
 * Checkout.com
 * Authorized and regulated as an electronic money institution
 * by the UK Financial Conduct Authority (FCA) under number 900816.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Checkout.com
 * @author    Platforms Development Team <platforms@checkout.com>
 * @copyright 2010-2019 Checkout.com
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://docs.checkout.com/
 */
?>

<p><?= __('Knet Mandate Info') ?></p>
</br>
<p><?= __('Post Date: <span>%1</span>', $block->escapeHtml($block->getData('postDate'))) ?></p>
<p><?= __('Amount: <span>%1</span>', $block->escapeHtml($block->getData('amount'))) ?></p>
<p><?= __('KNET Result code: <span>%1</span>', $block->escapeHtml($block->getData('resultCode'))) ?></p>
<p><?= __('KNET Payment ID: <span>%1</span>', $block->escapeHtml($block->getData('paymentId'))) ?></p>
<p><?= __('KNET Transaction ID: <span>%1</span>', $block->escapeHtml($block->getData('transactionId'))) ?></p>
<p><?= __('Auth code: <span>%1</span>', $block->escapeHtml($block->getData('authCode'))) ?></p>
<p><?= __('Reference: <span>%1</span>', $block->escapeHtml($block->getData('reference'))) ?></p>
