<?php

/**
 * Checkout.com
 * Authorized and regulated as an electronic money institution
 * by the UK Financial Conduct Authority (FCA) under number 900816.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Checkout.com
 * @author    Platforms Development Team <platforms@checkout.com>
 * @copyright 2010-present Checkout.com
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://docs.checkout.com/
 */
?>

<?= __('Post Date: <span>%1</span> ; ', $block->escapeHtml($block->getData('postDate'))) ?>
<?= __('Amount: <span>%1</span> ; ', $block->escapeHtml($block->getData('amount'))) ?>
<?= __('KNET Result code: <span>%1</span> ; ', $block->escapeHtml($block->getData('resultCode'))) ?>
<?= __('KNET Payment ID: <span>%1</span> ; ', $block->escapeHtml($block->getData('paymentId'))) ?>
<?= __('KNET Transaction ID: <span>%1</span> ; ', $block->escapeHtml($block->getData('transactionId'))) ?>
<?= __('Auth code: <span>%1</span> ; ', $block->escapeHtml($block->getData('authCode'))) ?>
<?= __('Reference: <span>%1</span> ; ', $block->escapeHtml($block->getData('reference'))) ?>
