<?php

/**
 * Checkout.com
 * Authorized and regulated as an electronic money institution
 * by the UK Financial Conduct Authority (FCA) under number 900816.
 *
 * PHP version 7
 *
 * @category  Magento2
 * @package   Checkout.com
 * @author    Platforms Development Team <platforms@checkout.com>
 * @copyright 2010-present Checkout.com
 * @license   https://opensource.org/licenses/mit-license.html MIT License
 * @link      https://docs.checkout.com/
 */
use Magento\Framework\Escaper;

/**
 * @var Escaper $escaper
 */
?>

<pre style="white-space:pre-wrap;">
<?= $escaper->escapeHtml($block->getData('output')) ?>
<?php if ($block->getData('link')): ?>
<br /><a href="<?= $escaper->escapeUrl($block->getData('link')) ?>" target="_blank" rel="noopener noreferrer"><?= $escaper->escapeUrl($block->getData('link')) ?></a>
<?php endif; ?>
</pre>
