<?php
/**
 * Checkout.com Magento 2 Payment module (https://www.checkout.com)
 *
 * Copyright (c) 2017 Checkout.com (https://www.checkout.com)
 * Author: David Fiaty | integration@checkout.com
 *
 * License GNU/GPL V3 https://www.gnu.org/licenses/gpl-3.0.en.html
 */
?>
 
<script src="<?php echo $block->getEmbeddedUrl(); ?>"></script>

<?php
// Load default CSS only if there is no custom file in config
if (!$block->hasCustomCss()) {
?>
	<style>
		@import url(<?php echo $block->getEmbeddedCss(); ?>);
	</style>
<?php
}
?>
<fieldset class="admin__fieldset payment-method checkout_com_admin_method" id="payment_form_checkout_com_admin_method" style="display: none;">
	<br>
	<div id="cko-form-holder">
		<form class="widget-container" id="embeddedForm" method="POST"></form>
		<input type="hidden" id="cko-card-token" name="cko-card-token">
	</div>
</fieldset>

<script>
	// Initialise the embedded form

	Frames.init({
		publicKey: '<?php echo $block->getPublicKey(); ?>',
		containerSelector: '#cko-form-holder',
		theme: '<?php echo $block->getEmbeddedTheme(); ?>',
		debugMode: <?php echo $block->getDebugMode(); ?>,
		localisation: '<?php echo $block->getIntegrationLanguage(); ?>',
		cardTokenised: function(event) {
			$('#cko-card-token').val(event.data.cardToken);
		},
	});
</script>