<?php
/**
 * Checkout.com Magento 2 Payment module (https://www.checkout.com)
 *
 * Copyright (c) 2017 Checkout.com (https://www.checkout.com)
 * Author: David Fiaty | integration@checkout.com
 *
 * License GNU/GPL V3 https://www.gnu.org/licenses/gpl-3.0.en.html
 */
?>
 
<?php
// Load default CSS only if there is no custom file in config
if (!$block->hasCustomCss()) {
?>
	<style>
		@import url(<?php echo $block->getEmbeddedCss(); ?>);
	</style>
<?php
}
?>
<fieldset class="admin__fieldset payment-method checkout_com_admin_method" id="payment_form_checkout_com_admin_method" style="display: none;">
	<br>
	<div id="cko-form-holder">
		<form class="widget-container" id="embeddedForm" method="POST"></form>
		<input type="hidden" id="ckoCardToken" name="ckoCardToken">
	</div>
	<br>
</fieldset>

<script>
    //<![CDATA[
    require(
        [
            'jquery',
			'framesjs',
            'domReady!'
        ], function($) {
			// Remove any existing event handlers
			Frames.removeAllEventHandlers(Frames.Events.CARD_VALIDATION_CHANGED);
			Frames.removeAllEventHandlers(Frames.Events.CARD_TOKENISED);
			Frames.removeAllEventHandlers(Frames.Events.FRAME_ACTIVATED);

			// Initialize the embedded form
			Frames.init({
				publicKey: '<?php echo $block->getPublicKey(); ?>',
				containerSelector: '#cko-form-holder',
				theme: '<?php echo $block->getEmbeddedTheme(); ?>',
				debugMode: <?php echo $block->getDebugMode(); ?>,
				localisation: '<?php echo $block->getIntegrationLanguage(); ?>',
				cardValidationChanged: function() {
					if (Frames.isCardValid()) {
						Frames.submitCard();
					}
				},
				cardTokenised: function(event) {
					$('#ckoCardToken').val(event.data.cardToken);
				}
			});
        });
    //]]>
</script>