<?php
/**
 * Checkout.com Magento 2 Payment module (https://www.checkout.com)
 *
 * Copyright (c) 2017 Checkout.com (https://www.checkout.com)
 * Author: David Fiaty | integration@checkout.com
 *
 * License GNU/GPL V3 https://www.gnu.org/licenses/gpl-3.0.en.html
 */
?>
 
<script src="<?php echo $block->getEmbeddedUrl(); ?>"></script>

<?php
// Load default CSS only if there is no custom file in config
if (!$block->hasCustomCss()) {
?>
	<style>
		@import url(<?php echo $block->getEmbeddedCss(); ?>);
	</style>
<?php
}
?>
<fieldset class="admin__fieldset payment-method checkout_com_admin_method" id="payment_form_checkout_com_admin_method" style="display: none;">
	<br>
	<div id="cko-form-holder">
		<form class="widget-container" id="embeddedForm" method="POST"></form>
	</div>
</fieldset>

<script>
	// Initialise the embedded form

	Frames.init({
		publicKey: '<?php echo $block->getPublicKey(); ?>',
		containerSelector: '#cko-form-holder',
		theme: '<?php echo $block->getEmbeddedTheme(); ?>',
		debugMode: <?php echo $block->getDebugMode(); ?>,
		localisation: '<?php echo $block->getIntegrationLanguage(); ?>',
		frameActivated: function () {
			//$('#ckoPlaceOrder').attr("disabled", true);
		},
		cardValidationChanged: function() {
			//self.updateButtonState(!(Frames.isCardValid() && quote.billingAddress() != null));
		},
		cardTokenised: function(event) {

			/*
			// Keep the card info
			self.card_bin = event.data.card.bin;

			// Save checkout info in PHP session
			self.saveSessionData();

			// Set the card token
			self.setCardTokenId(event.data.cardToken);

			// Add the card token to the form
			Frames.addCardToken(paymentForm, event.data.cardToken);

			// Place order
			window.location.replace(redirectUrl + '?cko-card-token=' + event.data.cardToken + '&cko-context-id=' + self.getEmailAddress());

			*/
		},
	});  

</script>