<div data-role="collapsible" id="<?= $block->getData('apm_id')?>" class="cko-apm <?= $block->getData('apm_id')?>">
    <div data-role="trigger">
        <span><?= $block->getData('apm_id')?></span>
    </div>
</div>
<div data-role="content" class="apm-content">
    <div class="input-group">
        <label class="icon" for="cpf">
        <span class="ckojs ckojs-card"></label>
        <input type="text" id="cpf" name="cpf" placeholder="<?= $block->escapeHtml(__('CPF')); ?>" class="input-control" data-validate="{'required':true}" pattern=".{11,11}">
    </div>
    <div class="input-group">
        <label class="icon" for="birthDate">
        <span class="ckojs ckojs-calendar"></label>
        <input type="text" id="birthDate" name="birthDate" placeholder="<?= $block->escapeHtml(__('Birth date')); ?>" class="input-control" data-validate="{'required':true}" pattern="\\d{1,2}/\\d{1,2}/\\d{4}">
    </div>
</div>