<div data-role="collapsible" id="<?= $block->escapeHtmlAttr($block->getData('apm_id'))?>" class="cko-apm <?= $block->escapeHtmlAttr($block->getData('apm_id'))?>">
    <div data-role="trigger">
		<span class="bg-<?= $block->escapeHtmlAttr($block->getData('apm_id'))?> bg-apm"></span>
        <span><?= $block->escapeHtml($block->getData('title'))?></span>
    </div>
</div>
<div data-role="content" class="apm-content">
    <form id="cko-apm-form-<?= $block->escapeHtmlAttr($block->getData('apm_id'))?>">
        <input type="hidden" name="source" value="<?= $block->escapeHtmlAttr($block->getData('apm_id'))?>" required>
        <div class="input-group">
            <label class="icon" for="bic">
            <span class="ckojs ckojs-card"></label>
            <input type="text" id="bic" name="bic" placeholder="<?= $block->escapeHtmlAttr(__('BIC')); ?>" class="input-control" required>
        </div>
        <br>
        <p align="center"><?= $block->escapeHtml(__('You will be redirected to an external page.'))?></p>
    </form>
</div>