<div data-role="collapsible" id="<?= $block->getData('apm_id')?>" class="cko-apm <?= $block->getData('apm_id')?>">
    <div data-role="trigger">
        <span><?= $block->getData('apm_id')?></span>
    </div>
</div>
<div data-role="content" class="apm-content">
    <form id="cko-apm-form-<?= $block->getData('apm_id')?>">
        <input type="hidden" name="source" value="<?= $block->getData('apm_id')?>">
        <div class="input-group">
            <label class="icon" for="bic">
            <span class="ckojs ckojs-card"></label>
            <input type="text" id="bic" name="bic" placeholder="<?= $block->escapeHtml(__('BIC')); ?>" class="input-control" data-validate="{'required':true}">
        </div>
        <div class="input-group">
            <label class="icon" for="purpose">
            <span class="ckojs ckojs-card"></label>
            <input type="text" id="purpose" name="purpose" placeholder="<?= $block->escapeHtml(__('Purpose')); ?>" class="input-control" data-validate="{'required':true}">
        </div>
        <br>
        <p align="center">You will be redirected to an external page.</p>
    </form>
</div>