<div data-role="collapsible" id="<?= $block->getData('apm_id')?>" class="cko-apm <?= $block->getData('apm_id')?>" tabindex="<?= $block->getData('tabIndex')?>">
    <div data-role="trigger">
		<span class="bg-<?= $block->getData('apm_id')?> bg-apm"><?= $block->getData('apm_id')?></span>
        <span><?= $block->getData('apm_id')?></span>
    </div>
</div>
<div data-role="content" class="apm-content">
    <form id="cko-apm-form-<?= $block->getData('apm_id')?>">
        <input type="hidden" name="source" value="<?= $block->getData('apm_id')?>">
        <div class="input-group">
            <label class="icon" for="bic">
            <span class="ckojs ckojs-card"></label>
            <input type="text" id="bic" name="bic" placeholder="<?= $block->escapeHtml(__('BIC')); ?>" class="input-control" data-validate="{'required':true}">
        </div>
        <div class="input-group">
            <label class="icon" for="description">
            <span class="ckojs ckojs-card"></label>
            <input type="text" id="description" name="description" placeholder="<?= $block->escapeHtml(__('Description')); ?>" class="input-control" data-validate="{'required':true}">
        </div>
        <div class="input-group">
            <label class="icon" for="language">
            <span class="ckojs ckojs-name"></label>
            <input type="text" id="language" name="language" placeholder="<?= $block->escapeHtml(__('Language')); ?>" class="input-control" data-validate="{'required':true}">
        </div>
        <br>
        <p align="center"><?= __('You will be redirected to an external page.')?></p>
    </form>
</div>