<div data-role="collapsible" id="<?= $block->getData('apm_id')?>" class="cko-apm <?= $block->getData('apm_id')?>">
    <div data-role="trigger">
		<span class="bg-<?= $block->getData('apm_id')?> bg-apm"></span>
        <span><?= $block->getData('title')?></span>
    </div>
</div>
<div data-role="content" class="apm-content <?= $block->getData('apm_id')?>">
    <form id="cko-apm-form-<?= $block->getData('apm_id')?>">
        <input type="hidden" name="source" value="<?= $block->getData('apm_id')?>" required>
        <input type="hidden" name="task" value="mandate">
        <div class="input-group">
            <label class="icon" for="bic">
            <span class="ckojs ckojs-card"></label>
            <input type="text" id="bic" name="bic" placeholder="<?= $block->escapeHtml(__('BIC')); ?>" class="input-control">
        </div>
        <div class="input-group">
            <label class="icon" for="account_iban">
            <span class="ckojs ckojs-card"></label>
            <input type="text" id="account_iban" name="account_iban" placeholder="<?= $block->escapeHtml(__('Account IBAN')); ?>" class="input-control" required>
        </div>
        <br>
        <p align="center">
            <?= __('You will be redirected to an external page.')?>
            <button type="button"><?= __('Continue')?></button>
        </p>
    </form>

    <script type="text/javascript">
        require(['jquery', 'CheckoutCom_Magento2/js/view/payment/utilities', 'Magento_Checkout/js/model/full-screen-loader', 'domReady!'], function ($, Utilities, FullScreenLoader) {
            // Prepare the form id
            var sepaForm = $('#' + 'cko-apm-form-<?= $block->getData('apm_id')?>');

            // Form click event
            sepaForm.find('button').on('click touch', function() {

                if(sepaForm.valid()) {

                    FullScreenLoader.startLoader();

                    // Prepare the data array
                    var formData = {};
                    sepaForm.serializeArray().forEach(function (elt) {
                        formData[elt.name] = elt.value;
                    });

                    // Send the request
                    $.ajax({
                        type: 'POST',
                        url: '<?= $block->getUrl('checkout_com/apm/displaysepa')?>',
                        data: formData,
                        success: function (data) {
                            if(data.html) {
                                sepaForm.html(data.html);
                                sepaForm.trigger('reset');
                            } else {
                                Utilities.showMessage('error', 'Invalid details.');
                            }

                            FullScreenLoader.stopLoader();
                        },
                        error: function (request, status, error) {
                            Utilities.showMessage('error', 'Invalid details.');
                            FullScreenLoader.stopLoader();
                        }
                    });

                }

            });
        });
    </script>
</div>
