<div data-role="collapsible" id="<?= $block->getData('apm_id')?>" class="cko-apm <?= $block->getData('apm_id')?>">
    <div data-role="trigger">
        <span><?= $block->getData('apm_id')?></span>
    </div>
</div>
<div data-role="content" class="apm-content">
    <form id="cko-apm-form-<?= $block->getData('apm_id')?>">
        <input type="hidden" name="source" value="<?= $block->getData('apm_id')?>">
        <div class="input-group">
            <label class="icon" for="bic">
            <span class="ckojs ckojs-card"></label>
            <input type="text" id="bic" name="bic" placeholder="<?= $block->escapeHtml(__('BIC')); ?>" class="input-control" data-validate="{'required':true}">
        </div>
        <div class="input-group">
            <label class="icon" for="account_iban">
            <span class="ckojs ckojs-card"></label>
            <input type="text" id="account_iban" name="account_iban" placeholder="<?= $block->escapeHtml(__('Account IBAN')); ?>" class="input-control" data-validate="{'required':true}">
        </div>
        <br>
        <p align="center">
            <?= __('You will be redirected to an external page.')?>
            <button><?= __('Continue')?></button>
        </p>
    </form>
</div>


<script type="text/javascript">
require(['jquery', 'domReady!'], function ($) {
    // Prepare the formm id
    var sepaform = $('#' + 'cko-apm-form-<?= $block->getData('apm_id')?>');

    // Form click event
    sepaform.on('click touch', function(e) {
        // Prevent default submission
        e.preventDefault();

        //  Prepare the payload
        var payload = $(this).serializeObject();

        console.log(payload);

        // Send the AJAX request
        $.ajax({
            type: 'POST',
            url: '<?= $block->getUrl('checkout_com/apm/displaysepa/getMandate')?>',
            data: payload,
            success: function (data) {

            },
            error: function (request, status, error) {

            }
        });
    });
});
</script>